// src/components/IssueEditor.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { getCurrentWindow } from "@tauri-apps/api/window";
  import { app, type EditorMode } from "../lib/store.svelte";
  import { api, errorMessage, swr } from "../lib/api";
  import type { CreateMeta, CreateMetaIssueType, FieldMetaMap, Issue, IssueFieldsInput, JiraUser, Named } from "../lib/types";
  import JiraHtml from "./JiraHtml.svelte";

  let { mode }: { mode: EditorMode } = $props();

  const isCreate = $derived(mode.kind === "create");
  const key = $derived(mode.kind === "edit" ? mode.key : null);

  // ---- form state ----------------------------------------------------------
  let summary = $state("");
  let description = $state("");
  let environment = $state("");
  let priorityId = $state("");
  let assignee = $state(""); // username; "" = leave as-is (edit) / default (create)
  let unassign = $state(false);
  let labels = $state("");
  let componentIds = $state<string[]>([]);
  let fixVersionIds = $state<string[]>([]);
  let duedate = $state("");
  let projectKey = $state("");
  let issueTypeId = $state("");
  let parentKey = $state("");

  let original = $state<Issue | null>(null);
  let meta = $state<FieldMetaMap | null>(null);
  let createMeta = $state<CreateMeta | null>(null);
  let loading = $state(true);
  let loadError = $state<string | null>(null);
  let saving = $state(false);
  let saveError = $state<string | null>(null);

  // ---- ui state ------------------------------------------------------------
  let fieldsOpen = $state(false);
  let preview = $state(false);
  let previewHtml = $state<string | null>(null);
  let previewBusy = $state(false);
  let confirmDiscard = $state(false);
  let textarea = $state<HTMLTextAreaElement | null>(null);
  let userHits = $state<JiraUser[]>([]);
  let fontSize = $state(16);

  const issueTypes = $derived<CreateMetaIssueType[]>(
    createMeta?.projects.find((p) => p.key === projectKey)?.issuetypes ?? [],
  );
  const issueType = $derived(issueTypes.find((t) => t.id === issueTypeId) ?? null);
  const fields = $derived<FieldMetaMap>(isCreate ? issueType?.fields ?? {} : meta ?? {});

  function has(name: string): boolean {
    return name in fields;
  }
  function allowed(name: string): Array<Named & { id: string }> {
    return (fields[name]?.allowedValues ?? []).filter((v): v is Named & { id: string } => typeof v.id === "string");
  }
  function ids(list: Named[] | undefined): string[] {
    return (list ?? []).flatMap((v) => (typeof v.id === "string" ? [v.id] : []));
  }

  const title = $derived(isCreate ? "New issue" : key ?? "");

  const dirty = $derived.by(() => {
    if (isCreate) return summary.trim() !== "" || description.trim() !== "";
    return Object.keys(buildUpdate()).length > 0;
  });

  // ---- load ----------------------------------------------------------------
  onMount(() => {
    window.addEventListener("keydown", onKeydown, true);
    void load();
    return () => window.removeEventListener("keydown", onKeydown, true);
  });

  async function load() {
    loading = true;
    loadError = null;
    try {
      if (mode.kind === "edit") await loadEdit(mode.key);
      else await loadCreate(mode.projectKey);
    } catch (e) {
      loadError = errorMessage(e);
    } finally {
      loading = false;
      queueMicrotask(() => textarea?.focus());
    }
  }

  async function loadEdit(k: string) {
    const [issueRes, editMeta] = await Promise.all([
      app.issue?.key === k ? Promise.resolve({ value: app.issue }) : api.getIssue(k, true).then((c) => c ?? api.getIssue(k, false)),
      api.getEditMeta(k).catch((e) => {
        app.notify(`Field metadata unavailable: ${errorMessage(e)}`, "error");
        return null;
      }),
    ]);
    const issue = issueRes?.value;
    if (!issue) throw new Error(`Issue ${k} not found`);
    original = issue;
    meta = editMeta?.fields ?? fallbackMeta();
    const f = issue.fields;
    summary = f.summary ?? "";
    description = f.description ?? "";
    environment = f.environment ?? "";
    priorityId = f.priority?.id ?? "";
    labels = (f.labels ?? []).join(" ");
    componentIds = ids(f.components);
    fixVersionIds = ids(f.fixVersions);
    duedate = f.duedate ?? "";
    projectKey = f.project?.key ?? "";
  }

  async function loadCreate(preferred: string | null) {
    fieldsOpen = true;
    if (!app.projects.length) await app.loadSidebar();
    projectKey = preferred ?? app.projects[0]?.key ?? "";
    if (!projectKey) throw new Error("No projects available to create an issue in");
    await loadCreateMeta(projectKey);
  }

  async function loadCreateMeta(pk: string) {
    createMeta = null;
    await swr<CreateMeta>(
      (pc) => api.getCreateMeta(pk, pc),
      (v) => {
        createMeta = v;
        const types = v.projects.find((p) => p.key === pk)?.issuetypes ?? [];
        if (!types.some((t) => t.id === issueTypeId)) {
          issueTypeId = (types.find((t) => !t.subtask && /task/i.test(t.name)) ?? types.find((t) => !t.subtask) ?? types[0])?.id ?? "";
        }
      },
    );
  }

  function fallbackMeta(): FieldMetaMap {
    const s = (name: string, type: string) => ({ required: false, name, schema: { type } });
    return {
      summary: { ...s("Summary", "string"), required: true },
      description: s("Description", "string"),
      labels: s("Labels", "array"),
      duedate: s("Due Date", "date"),
      assignee: s("Assignee", "user"),
    };
  }

  function onProjectChange() {
    issueTypeId = "";
    void loadCreateMeta(projectKey).catch((e) => app.notify(errorMessage(e), "error"));
  }

  // ---- payload -------------------------------------------------------------
  function parsedLabels(): string[] {
    return labels
      .split(/[\s,]+/)
      .map((l) => l.trim())
      .filter(Boolean);
  }

  function sameSet(a: string[], b: string[]): boolean {
    return a.length === b.length && a.every((x) => b.includes(x));
  }

  function buildUpdate(): IssueFieldsInput {
    const f = original?.fields;
    if (!f) return {};
    const out: IssueFieldsInput = {};
    if (summary !== (f.summary ?? "")) out.summary = summary;
    if (description !== (f.description ?? "")) out.description = description || null;
    if (has("environment") && environment !== (f.environment ?? "")) out.environment = environment || null;
    if (has("priority") && priorityId && priorityId !== (f.priority?.id ?? "")) out.priority = { id: priorityId };
    if (has("labels") && !sameSet(parsedLabels(), f.labels ?? [])) out.labels = parsedLabels();
    if (has("components") && !sameSet(componentIds, ids(f.components))) {
      out.components = componentIds.map((id) => ({ id }));
    }
    if (has("fixVersions") && !sameSet(fixVersionIds, ids(f.fixVersions))) {
      out.fixVersions = fixVersionIds.map((id) => ({ id }));
    }
    if (has("duedate") && duedate !== (f.duedate ?? "")) out.duedate = duedate || null;
    if (has("assignee")) {
      if (unassign && f.assignee) out.assignee = { name: null };
      else if (!unassign && assignee.trim() && assignee.trim() !== (f.assignee?.name ?? "")) out.assignee = { name: assignee.trim() };
    }
    return out;
  }

  function buildCreate(): IssueFieldsInput {
    const out: IssueFieldsInput = {
      project: { key: projectKey },
      issuetype: { id: issueTypeId },
      summary: summary.trim(),
    };
    if (description.trim()) out.description = description;
    if (has("environment") && environment.trim()) out.environment = environment;
    if (has("priority") && priorityId) out.priority = { id: priorityId };
    if (has("labels") && parsedLabels().length) out.labels = parsedLabels();
    if (has("components") && componentIds.length) out.components = componentIds.map((id) => ({ id }));
    if (has("fixVersions") && fixVersionIds.length) out.fixVersions = fixVersionIds.map((id) => ({ id }));
    if (has("duedate") && duedate) out.duedate = duedate;
    if (has("assignee") && assignee.trim()) out.assignee = { name: assignee.trim() };
    if (issueType?.subtask && parentKey.trim()) out.parent = { key: parentKey.trim().toUpperCase() };
    return out;
  }

  async function save() {
    if (saving || loading) return;
    saveError = null;
    if (!summary.trim()) {
      saveError = "Summary is required.";
      fieldsOpen = true;
      return;
    }
    if (isCreate && (!projectKey || !issueTypeId)) {
      saveError = "Project and issue type are required.";
      fieldsOpen = true;
      return;
    }
    saving = true;
    try {
      if (mode.kind === "edit") {
        const changes = buildUpdate();
        if (Object.keys(changes).length) {
          const updated = await api.updateIssue(mode.key, changes);
          app.applyIssue(updated);
          app.notify(`${mode.key} saved`);
        }
      } else {
        const created = await api.createIssue(buildCreate());
        app.notify(`${created.key} created`);
        app.addCreatedIssue(created);
      }
      app.closeEditor();
    } catch (e) {
      saveError = errorMessage(e);
      fieldsOpen = true;
    } finally {
      saving = false;
    }
  }

  function cancel() {
    if (dirty && !confirmDiscard) {
      confirmDiscard = true;
      return;
    }
    app.closeEditor();
  }

  // ---- preview -------------------------------------------------------------
  let previewTimer: ReturnType<typeof setTimeout> | undefined;
  $effect(() => {
    if (!preview) return;
    const text = description;
    clearTimeout(previewTimer);
    previewTimer = setTimeout(async () => {
      previewBusy = true;
      try {
        previewHtml = text.trim() ? await api.renderWiki(text, key ?? undefined) : "";
      } catch (e) {
        previewHtml = `<p class="muted">Preview unavailable: ${errorMessage(e)}</p>`;
      } finally {
        previewBusy = false;
      }
    }, 350);
  });

  // ---- users ---------------------------------------------------------------
  let userTimer: ReturnType<typeof setTimeout> | undefined;
  function onAssigneeInput() {
    unassign = false;
    clearTimeout(userTimer);
    const q = assignee.trim();
    if (q.length < 2) {
      userHits = [];
      return;
    }
    userTimer = setTimeout(async () => {
      try {
        userHits = await api.searchUsers(q);
      } catch {
        userHits = [];
      }
    }, 250);
  }

  // ---- keyboard ------------------------------------------------------------
  function onKeydown(e: KeyboardEvent) {
    if (e.key === "F11") return; // App toggles OS fullscreen
    const mod = e.ctrlKey || e.metaKey;
    if (mod && (e.key === "s" || e.key === "Enter")) {
      e.preventDefault();
      void save();
    } else if (mod && e.key === "b") {
      e.preventDefault();
      fieldsOpen = !fieldsOpen;
    } else if (mod && e.key === "p") {
      e.preventDefault();
      preview = !preview;
    } else if (e.key === "Escape") {
      e.preventDefault();
      if (confirmDiscard) confirmDiscard = false;
      else if (userHits.length) userHits = [];
      else if (fieldsOpen && !isCreate) fieldsOpen = false;
      else cancel();
    }
  }

  async function toggleOsFullscreen() {
    const w = getCurrentWindow();
    await w.setFullscreen(!(await w.isFullscreen()));
  }

  function insertTab(e: KeyboardEvent) {
    if (e.key !== "Tab" || !textarea) return;
    e.preventDefault();
    const { selectionStart: s, selectionEnd: en } = textarea;
    description = description.slice(0, s) + "  " + description.slice(en);
    queueMicrotask(() => textarea?.setSelectionRange(s + 2, s + 2));
  }

  function toggleIn(list: string[], id: string): string[] {
    return list.includes(id) ? list.filter((x) => x !== id) : [...list, id];
  }
</script>

<div class="editor" class:fields-open={fieldsOpen} class:preview>
  <header class="bar">
    <button class="ghost" class:on={fieldsOpen} onclick={() => (fieldsOpen = !fieldsOpen)} title="Show / hide fields (Ctrl+B)">
      ☰ Fields
    </button>
    <span class="title">
      <span class="mono key">{title}</span>
      {#if !isCreate && summary}<span class="sep muted">·</span><span class="muted ellipsis">{summary}</span>{/if}
      {#if dirty}<span class="dot" title="Unsaved changes"></span>{/if}
    </span>
    <span class="grow"></span>
    <button class="ghost" onclick={() => (fontSize = Math.max(12, fontSize - 1))} title="Smaller text">A−</button>
    <button class="ghost" onclick={() => (fontSize = Math.min(28, fontSize + 1))} title="Larger text">A+</button>
    <button class="ghost" class:on={preview} onclick={() => (preview = !preview)} title="Live preview (Ctrl+P)">
      👁 Preview
    </button>
    <button class="ghost" onclick={toggleOsFullscreen} title="Toggle fullscreen (F11)">⛶</button>
    <button class="ghost" onclick={cancel} disabled={saving}>Cancel</button>
    <button class="primary" onclick={save} disabled={saving || loading || (!isCreate && !dirty)} title="Save (Ctrl+S)">
      {#if saving}<span class="spin"></span>{/if}
      {isCreate ? "Create" : "Save"}
    </button>
  </header>

  {#if confirmDiscard}
    <div class="banner warn">
      Discard unsaved changes?
      <button onclick={() => app.closeEditor()}>Discard</button>
      <button class="ghost" onclick={() => (confirmDiscard = false)}>Keep editing</button>
    </div>
  {/if}
  {#if saveError}
    <div class="banner error">{saveError}</div>
  {/if}

  <div class="body">
    {#if fieldsOpen}
      <aside class="fields">
        {#if loading}
          <div class="muted"><span class="spin"></span> Loading fields…</div>
        {:else if loadError}
          <div class="error">{loadError}</div>
        {:else}
          {#if isCreate}
            <label>
              <span>Project</span>
              <select bind:value={projectKey} onchange={onProjectChange}>
                {#each app.projects as p (p.key)}
                  <option value={p.key}>{p.key} · {p.name}</option>
                {/each}
              </select>
            </label>
            <label>
              <span>Issue type</span>
              <select bind:value={issueTypeId} disabled={!issueTypes.length}>
                {#each issueTypes as t (t.id)}
                  <option value={t.id}>{t.name}</option>
                {/each}
              </select>
            </label>
            {#if issueType?.subtask}
              <label>
                <span>Parent issue</span>
                <input bind:value={parentKey} placeholder="{projectKey}-123" spellcheck="false" />
              </label>
            {/if}
          {/if}

          <label>
            <span>Summary <b class="req">*</b></span>
            <input bind:value={summary} placeholder="What needs to be done?" />
          </label>

          {#if has("priority")}
            <label>
              <span>Priority</span>
              <select bind:value={priorityId}>
                {#if isCreate}<option value="">Default</option>{/if}
                {#each allowed("priority") as p (p.id)}
                  <option value={p.id}>{p.name}</option>
                {/each}
              </select>
            </label>
          {/if}

          {#if has("assignee")}
            <label class="assignee">
              <span>Assignee</span>
              {#if !isCreate && original?.fields.assignee && !unassign && !assignee}
                <div class="current muted">Currently {original.fields.assignee.displayName}</div>
              {/if}
              <input
                bind:value={assignee}
                oninput={onAssigneeInput}
                placeholder={unassign ? "Unassigned" : "username"}
                spellcheck="false"
                autocomplete="off"
              />
              {#if userHits.length}
                <div class="hits">
                  {#each userHits as u (u.name)}
                    <button class="ghost hit" onclick={() => { assignee = u.name; userHits = []; }}>
                      {u.displayName} <span class="muted">({u.name})</span>
                    </button>
                  {/each}
                </div>
              {/if}
              <div class="row">
                {#if app.me}<button class="ghost small" onclick={() => { assignee = app.me?.name ?? ""; unassign = false; }}>Me</button>{/if}
                {#if !isCreate}<button class="ghost small" class:on={unassign} onclick={() => { unassign = !unassign; assignee = ""; }}>Unassign</button>{/if}
              </div>
            </label>
          {/if}

          {#if has("labels")}
            <label>
              <span>Labels</span>
              <input bind:value={labels} placeholder="space separated" spellcheck="false" />
            </label>
          {/if}

          {#if has("components") && allowed("components").length}
            <fieldset>
              <legend>Components</legend>
              {#each allowed("components") as c (c.id)}
                <label class="check">
                  <input type="checkbox" checked={componentIds.includes(c.id)} onchange={() => (componentIds = toggleIn(componentIds, c.id))} />
                  {c.name}
                </label>
              {/each}
            </fieldset>
          {/if}

          {#if has("fixVersions") && allowed("fixVersions").length}
            <fieldset>
              <legend>Fix versions</legend>
              {#each allowed("fixVersions") as v (v.id)}
                <label class="check">
                  <input type="checkbox" checked={fixVersionIds.includes(v.id)} onchange={() => (fixVersionIds = toggleIn(fixVersionIds, v.id))} />
                  {v.name}
                </label>
              {/each}
            </fieldset>
          {/if}

          {#if has("duedate")}
            <label>
              <span>Due date</span>
              <input type="date" bind:value={duedate} />
            </label>
          {/if}

          {#if has("environment")}
            <label>
              <span>Environment</span>
              <textarea bind:value={environment} rows="3" placeholder="Wiki markup"></textarea>
            </label>
          {/if}
        {/if}
      </aside>
    {/if}

    <main class="zen">
      {#if loading}
        <div class="center muted"><span class="spin"></span></div>
      {:else if loadError && !isCreate}
        <div class="center error">{loadError}</div>
      {:else}
        <input
          class="summary"
          bind:value={summary}
          placeholder="Summary"
          style:font-size="{fontSize + 8}px"
          spellcheck="true"
        />
        <div class="panes">
          <textarea
            bind:this={textarea}
            bind:value={description}
            onkeydown={insertTab}
            style:font-size="{fontSize}px"
            placeholder="Description in Jira wiki markup — h2. Heading, *bold*, _italic_, {'{code}'}…{'{code}'}, * bullets, [~user]"
            spellcheck="true"
            disabled={saving}
          ></textarea>
          {#if preview}
            <div class="preview-pane" style:font-size="{fontSize}px">
              {#if previewBusy}<span class="spin float"></span>{/if}
              {#if previewHtml === null}
                <p class="muted">Rendering…</p>
              {:else if previewHtml === ""}
                <p class="muted">Nothing to preview.</p>
              {:else}
                <JiraHtml html={previewHtml} class="description" />
              {/if}
            </div>
          {/if}
        </div>
        <footer class="hint muted">
          Wiki markup · <kbd>Ctrl</kbd>+<kbd>S</kbd> save · <kbd>Ctrl</kbd>+<kbd>B</kbd> fields · <kbd>Ctrl</kbd>+<kbd>P</kbd> preview · <kbd>Esc</kbd> cancel
        </footer>
      {/if}
    </main>
  </div>
</div>

<style>
  .editor {
    position: fixed;
    inset: 0;
    display: flex;
    flex-direction: column;
    background: var(--bg);
    z-index: 20;
  }
  .bar {
    display: flex;
    align-items: center;
    gap: 4px;
    padding: 6px 10px;
    border-bottom: 1px solid var(--border);
    flex-shrink: 0;
  }
  .bar .title {
    display: flex;
    align-items: center;
    gap: 6px;
    min-width: 0;
    margin-left: 6px;
  }
  .key {
    font-weight: 600;
  }
  .ellipsis {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    max-width: 40vw;
  }
  .dot {
    width: 8px;
    height: 8px;
    border-radius: 50%;
    background: var(--warn);
    flex-shrink: 0;
  }
  .grow {
    flex: 1;
  }
  button.on {
    background: var(--accent-bg);
    color: var(--accent);
  }
  .banner {
    padding: 8px 14px;
    display: flex;
    align-items: center;
    gap: 10px;
    flex-shrink: 0;
  }
  .banner.warn {
    background: var(--warn-bg);
  }
  .banner.error {
    background: var(--danger-bg);
    color: var(--danger);
  }
  .body {
    flex: 1;
    display: flex;
    min-height: 0;
  }
  .fields {
    width: 300px;
    flex-shrink: 0;
    border-right: 1px solid var(--border);
    background: var(--bg-2);
    overflow-y: auto;
    padding: 12px 14px 24px;
    display: flex;
    flex-direction: column;
    gap: 12px;
  }
  .fields label {
    display: flex;
    flex-direction: column;
    gap: 4px;
    font-size: 13px;
  }
  .fields label > span {
    color: var(--fg-2);
    font-weight: 600;
    font-size: 12px;
    text-transform: uppercase;
    letter-spacing: 0.02em;
  }
  .req {
    color: var(--danger);
  }
  .fields input,
  .fields select,
  .fields textarea {
    width: 100%;
  }
  .fields fieldset {
    border: 1px solid var(--border);
    border-radius: var(--radius);
    padding: 6px 10px 8px;
    margin: 0;
    display: flex;
    flex-direction: column;
    gap: 4px;
  }
  .fields legend {
    color: var(--fg-2);
    font-weight: 600;
    font-size: 12px;
    text-transform: uppercase;
    padding: 0 4px;
  }
  .check {
    flex-direction: row !important;
    align-items: center;
    gap: 8px !important;
  }
  .check input {
    width: auto;
  }
  .assignee .row {
    display: flex;
    gap: 6px;
  }
  .small {
    padding: 2px 8px;
    font-size: 12px;
  }
  .current {
    font-size: 12px;
  }
  .hits {
    display: flex;
    flex-direction: column;
    border: 1px solid var(--border);
    border-radius: var(--radius);
    background: var(--bg);
    max-height: 160px;
    overflow-y: auto;
  }
  .hit {
    text-align: left;
    border-radius: 0;
  }
  .error {
    color: var(--danger);
  }

  .zen {
    flex: 1;
    min-width: 0;
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 20px 32px 8px;
  }
  .zen > * {
    width: 100%;
    max-width: var(--content-width);
  }
  .editor.preview .zen > .panes {
    max-width: none;
  }
  .summary {
    border: none;
    border-bottom: 2px solid transparent;
    border-radius: 0;
    padding: 4px 0 8px;
    font-weight: 600;
    line-height: 1.25;
    background: transparent;
  }
  .summary:focus {
    border-bottom-color: var(--accent);
  }
  .panes {
    flex: 1;
    min-height: 0;
    display: flex;
    gap: 24px;
    margin-top: 12px;
  }
  .panes > textarea {
    flex: 1;
    min-width: 0;
    height: 100%;
    resize: none;
    border: none;
    padding: 8px 0;
    background: transparent;
    font-family: var(--mono);
    line-height: 1.6;
    tab-size: 2;
  }
  .panes > textarea:focus {
    border: none;
  }
  .preview-pane {
    flex: 1;
    min-width: 0;
    overflow-y: auto;
    padding: 8px 16px;
    border-left: 1px solid var(--border);
    position: relative;
    line-height: 1.6;
  }
  .spin.float {
    position: absolute;
    top: 8px;
    right: 8px;
  }
  .hint {
    font-size: 12px;
    padding-top: 6px;
    flex-shrink: 0;
  }
  .center {
    flex: 1;
    display: grid;
    place-items: center;
  }
  kbd {
    font-family: var(--mono);
    font-size: 11px;
    border: 1px solid var(--border);
    border-bottom-width: 2px;
    border-radius: 3px;
    padding: 0 4px;
    background: var(--bg-2);
  }
</style>

// src/components/IssueEditor.tsx
import { useCallback, useEffect, useMemo, useRef, useState, type KeyboardEvent as ReactKeyboardEvent } from "react";
import { getCurrentWindow } from "@tauri-apps/api/window";
import type { Editor } from "@tiptap/react";
import { app, useApp, useBaseUrl, type EditorMode } from "../lib/store";
import { api, errorMessage, swr } from "../lib/api";
import type { CreateMeta, CreateMetaIssueType, FieldMetaMap, Issue, IssueFieldsInput, JiraUser, Named } from "../lib/types";
import { htmlToWiki, renderedToEditorHtml, roundTrips } from "../lib/wiki";
import RichEditor from "./RichEditor";
import css from "./IssueEditor.module.css";

type DescMode = "rich" | "markup";

interface Form {
  summary: string;
  description: string;
  environment: string;
  priorityId: string;
  assignee: string;
  unassign: boolean;
  labels: string;
  componentIds: string[];
  fixVersionIds: string[];
  duedate: string;
  projectKey: string;
  issueTypeId: string;
  parentKey: string;
}

const EMPTY_FORM: Form = {
  summary: "",
  description: "",
  environment: "",
  priorityId: "",
  assignee: "",
  unassign: false,
  labels: "",
  componentIds: [],
  fixVersionIds: [],
  duedate: "",
  projectKey: "",
  issueTypeId: "",
  parentKey: "",
};

function fallbackMeta(): FieldMetaMap {
  const s = (name: string, type: string) => ({ required: false, name, schema: { type } });
  return {
    summary: { ...s("Summary", "string"), required: true },
    description: s("Description", "string"),
    labels: s("Labels", "array"),
    duedate: s("Due Date", "date"),
    assignee: s("Assignee", "user"),
  };
}

function ids(list: Named[] | undefined): string[] {
  return (list ?? []).flatMap((v) => (typeof v.id === "string" ? [v.id] : []));
}

function parseLabels(labels: string): string[] {
  return labels
    .split(/[\s,]+/)
    .map((l) => l.trim())
    .filter(Boolean);
}

function sameSet(a: string[], b: string[]): boolean {
  return a.length === b.length && a.every((x) => b.includes(x));
}

function toggleIn(list: string[], id: string): string[] {
  return list.includes(id) ? list.filter((x) => x !== id) : [...list, id];
}

async function toggleOsFullscreen() {
  const w = getCurrentWindow();
  await w.setFullscreen(!(await w.isFullscreen()));
}

export default function IssueEditor({ mode }: { mode: EditorMode }) {
  const isCreate = mode.kind === "create";
  const key = mode.kind === "edit" ? mode.key : null;
  const baseUrl = useBaseUrl();
  const projects = useApp((s) => s.projects);
  const me = useApp((s) => s.me);

  const [form, setForm] = useState<Form>(EMPTY_FORM);
  const patch = useCallback((p: Partial<Form>) => setForm((f) => ({ ...f, ...p })), []);

  const [original, setOriginal] = useState<Issue | null>(null);
  const [meta, setMeta] = useState<FieldMetaMap | null>(null);
  const [createMeta, setCreateMeta] = useState<CreateMeta | null>(null);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);

  const [fieldsOpen, setFieldsOpen] = useState(isCreate);
  const [confirmDiscard, setConfirmDiscard] = useState(false);
  const [userHits, setUserHits] = useState<JiraUser[]>([]);
  const [fontSize, setFontSize] = useState(16);

  // Description editing: rich (TipTap) or raw wiki markup. `form.description`
  // is always the markup; rich edits are converted on every change.
  const [descMode, setDescMode] = useState<DescMode>("rich");
  const [richHtml, setRichHtml] = useState<string | null>(null);
  const [richKey, setRichKey] = useState(0);
  const [richBusy, setRichBusy] = useState(false);
  const [lossy, setLossy] = useState(false);
  const richSource = useRef("");
  const textarea = useRef<HTMLTextAreaElement>(null);
  const summaryInput = useRef<HTMLInputElement>(null);

  const issueTypes = useMemo<CreateMetaIssueType[]>(
    () => createMeta?.projects.find((p) => p.key === form.projectKey)?.issuetypes ?? [],
    [createMeta, form.projectKey],
  );
  const issueType = issueTypes.find((t) => t.id === form.issueTypeId) ?? null;
  const fields: FieldMetaMap = isCreate ? (issueType?.fields ?? {}) : (meta ?? {});
  const has = (name: string) => name in fields;
  const allowed = (name: string): Array<Named & { id: string }> =>
    (fields[name]?.allowedValues ?? []).filter((v): v is Named & { id: string } => typeof v.id === "string");

  const title = isCreate ? "New issue" : (key ?? "");

  // ---- load ----------------------------------------------------------------
  useEffect(() => {
    let cancelled = false;
    (async () => {
      setLoading(true);
      setLoadError(null);
      try {
        if (mode.kind === "edit") await loadEdit(mode.key);
        else await loadCreate(mode.projectKey);
      } catch (e) {
        if (!cancelled) setLoadError(errorMessage(e));
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  async function loadEdit(k: string) {
    const cur = app.state.issue;
    const [issueRes, editMeta] = await Promise.all([
      cur?.key === k ? Promise.resolve({ value: cur }) : api.getIssue(k, true).then((c) => c ?? api.getIssue(k, false)),
      api.getEditMeta(k).catch((e) => {
        app.notify(`Field metadata unavailable: ${errorMessage(e)}`, "error");
        return null;
      }),
    ]);
    const issue = issueRes?.value;
    if (!issue) throw new Error(`Issue ${k} not found`);
    setOriginal(issue);
    setMeta(editMeta?.fields ?? fallbackMeta());
    const f = issue.fields;
    setForm({
      ...EMPTY_FORM,
      summary: f.summary ?? "",
      description: f.description ?? "",
      environment: f.environment ?? "",
      priorityId: f.priority?.id ?? "",
      labels: (f.labels ?? []).join(" "),
      componentIds: ids(f.components),
      fixVersionIds: ids(f.fixVersions),
      duedate: f.duedate ?? "",
      projectKey: f.project?.key ?? "",
    });
    const rendered = issue.renderedFields?.description;
    await enterRich(f.description ?? "", typeof rendered === "string" ? rendered : null);
  }

  async function loadCreate(preferred: string | null) {
    if (!app.state.projects.length) await app.loadSidebar();
    const pk = preferred ?? app.state.projects[0]?.key ?? "";
    if (!pk) throw new Error("No projects available to create an issue in");
    patch({ projectKey: pk });
    setRichHtml("");
    await loadCreateMeta(pk);
  }

  async function loadCreateMeta(pk: string) {
    setCreateMeta(null);
    await swr<CreateMeta>(
      (pc) => api.getCreateMeta(pk, pc),
      (v) => {
        setCreateMeta(v);
        const types = v.projects.find((p) => p.key === pk)?.issuetypes ?? [];
        setForm((f) => {
          if (types.some((t) => t.id === f.issueTypeId)) return f;
          const pick = types.find((t) => !t.subtask && /task/i.test(t.name)) ?? types.find((t) => !t.subtask) ?? types[0];
          return { ...f, issueTypeId: pick?.id ?? "" };
        });
      },
    );
  }

  function onProjectChange(pk: string) {
    patch({ projectKey: pk, issueTypeId: "" });
    void loadCreateMeta(pk).catch((e) => app.notify(errorMessage(e), "error"));
  }

  // ---- description modes ---------------------------------------------------
  /** Load `markup` into the rich editor (rendering through Jira unless `rendered` is given). */
  async function enterRich(markup: string, rendered: string | null = null) {
    setRichBusy(true);
    try {
      const html = markup.trim() ? (rendered ?? (await api.renderWiki(markup, key ?? undefined))) : "";
      richSource.current = markup;
      setRichHtml(renderedToEditorHtml(html, baseUrl));
      setRichKey((n) => n + 1);
      setDescMode("rich");
    } catch (e) {
      app.notify(`Rich editor unavailable: ${errorMessage(e)}`, "error");
      setDescMode("markup");
    } finally {
      setRichBusy(false);
    }
  }

  function onRichReady(editor: Editor) {
    const markup = richSource.current;
    setLossy(markup.trim() !== "" && !roundTrips(markup, editor.getHTML()));
  }

  function onRichChange(editor: Editor) {
    patch({ description: editor.isEmpty ? "" : htmlToWiki(editor.getHTML()) });
  }

  function toggleDescMode() {
    if (richBusy) return;
    if (descMode === "rich") {
      setDescMode("markup");
      setLossy(false);
      queueMicrotask(() => textarea.current?.focus());
    } else {
      void enterRich(form.description);
    }
  }

  // ---- payload -------------------------------------------------------------
  function buildUpdate(): IssueFieldsInput {
    const f = original?.fields;
    if (!f) return {};
    const out: IssueFieldsInput = {};
    if (form.summary !== (f.summary ?? "")) out.summary = form.summary;
    if (form.description !== (f.description ?? "")) out.description = form.description || null;
    if (has("environment") && form.environment !== (f.environment ?? "")) out.environment = form.environment || null;
    if (has("priority") && form.priorityId && form.priorityId !== (f.priority?.id ?? "")) out.priority = { id: form.priorityId };
    if (has("labels") && !sameSet(parseLabels(form.labels), f.labels ?? [])) out.labels = parseLabels(form.labels);
    if (has("components") && !sameSet(form.componentIds, ids(f.components))) out.components = form.componentIds.map((id) => ({ id }));
    if (has("fixVersions") && !sameSet(form.fixVersionIds, ids(f.fixVersions))) out.fixVersions = form.fixVersionIds.map((id) => ({ id }));
    if (has("duedate") && form.duedate !== (f.duedate ?? "")) out.duedate = form.duedate || null;
    if (has("assignee")) {
      const a = form.assignee.trim();
      if (form.unassign && f.assignee) out.assignee = { name: null };
      else if (!form.unassign && a && a !== (f.assignee?.name ?? "")) out.assignee = { name: a };
    }
    return out;
  }

  function buildCreate(): IssueFieldsInput {
    const out: IssueFieldsInput = {
      project: { key: form.projectKey },
      issuetype: { id: form.issueTypeId },
      summary: form.summary.trim(),
    };
    if (form.description.trim()) out.description = form.description;
    if (has("environment") && form.environment.trim()) out.environment = form.environment;
    if (has("priority") && form.priorityId) out.priority = { id: form.priorityId };
    if (has("labels") && parseLabels(form.labels).length) out.labels = parseLabels(form.labels);
    if (has("components") && form.componentIds.length) out.components = form.componentIds.map((id) => ({ id }));
    if (has("fixVersions") && form.fixVersionIds.length) out.fixVersions = form.fixVersionIds.map((id) => ({ id }));
    if (has("duedate") && form.duedate) out.duedate = form.duedate;
    if (has("assignee") && form.assignee.trim()) out.assignee = { name: form.assignee.trim() };
    if (issueType?.subtask && form.parentKey.trim()) out.parent = { key: form.parentKey.trim().toUpperCase() };
    return out;
  }

  const dirty = isCreate ? form.summary.trim() !== "" || form.description.trim() !== "" : Object.keys(buildUpdate()).length > 0;

  async function save() {
    if (saving || loading) return;
    setSaveError(null);
    if (!form.summary.trim()) {
      setSaveError("Summary is required.");
      summaryInput.current?.focus();
      return;
    }
    if (isCreate && (!form.projectKey || !form.issueTypeId)) {
      setSaveError("Project and issue type are required.");
      setFieldsOpen(true);
      return;
    }
    setSaving(true);
    try {
      if (mode.kind === "edit") {
        const changes = buildUpdate();
        if (Object.keys(changes).length) {
          const updated = await api.updateIssue(mode.key, changes);
          app.applyIssue(updated);
          app.notify(`${mode.key} saved`);
        }
      } else {
        const created = await api.createIssue(buildCreate());
        app.notify(`${created.key} created`);
        app.addCreatedIssue(created);
      }
      app.closeEditor();
    } catch (e) {
      setSaveError(errorMessage(e));
      setFieldsOpen(true);
    } finally {
      setSaving(false);
    }
  }

  function cancel() {
    if (dirty && !confirmDiscard) {
      setConfirmDiscard(true);
      return;
    }
    app.closeEditor();
  }

  // ---- users ---------------------------------------------------------------
  const userTimer = useRef<ReturnType<typeof setTimeout>>(undefined);
  function onAssigneeInput(value: string) {
    patch({ assignee: value, unassign: false });
    clearTimeout(userTimer.current);
    const q = value.trim();
    if (q.length < 2) {
      setUserHits([]);
      return;
    }
    userTimer.current = setTimeout(async () => {
      try {
        setUserHits(await api.searchUsers(q));
      } catch {
        setUserHits([]);
      }
    }, 250);
  }

  // ---- keyboard ------------------------------------------------------------
  const latest = useRef({ save, cancel, toggleDescMode, confirmDiscard, hasHits: userHits.length > 0, fieldsOpen, description: form.description });
  latest.current = { save, cancel, toggleDescMode, confirmDiscard, hasHits: userHits.length > 0, fieldsOpen, description: form.description };

  useEffect(() => {
    function onKeydown(e: KeyboardEvent) {
      if (e.key === "F11") return;
      const l = latest.current;
      const mod = e.ctrlKey || e.metaKey;
      const inRich = e.target instanceof HTMLElement && e.target.closest(".ProseMirror") !== null;
      if (mod && (e.key === "s" || e.key === "Enter")) {
        e.preventDefault();
        void l.save();
      } else if (mod && ((e.key.toLowerCase() === "b" && !inRich) || (e.shiftKey && e.key.toLowerCase() === "f"))) {
        e.preventDefault();
        setFieldsOpen((v) => !v);
      } else if (mod && e.key === "p") {
        e.preventDefault();
        l.toggleDescMode();
      } else if (e.key === "Escape") {
        e.preventDefault();
        if (l.confirmDiscard) setConfirmDiscard(false);
        else if (l.hasHits) setUserHits([]);
        else if (l.fieldsOpen && !isCreate) setFieldsOpen(false);
        else l.cancel();
      }
    }
    window.addEventListener("keydown", onKeydown, true);
    return () => window.removeEventListener("keydown", onKeydown, true);
  }, [isCreate]);

  function insertTab(e: ReactKeyboardEvent<HTMLTextAreaElement>) {
    if (e.key !== "Tab") return;
    e.preventDefault();
    const ta = e.currentTarget;
    const { selectionStart: s, selectionEnd: en } = ta;
    patch({ description: form.description.slice(0, s) + "  " + form.description.slice(en) });
    queueMicrotask(() => ta.setSelectionRange(s + 2, s + 2));
  }

  function openImage(src: string, alt: string) {
    app.openLightbox([{ src, title: alt || "Image" }], 0);
  }

  // ---- render --------------------------------------------------------------
  return (
    <div className={`${css.editor} ${fieldsOpen ? css.fieldsOpen : ""}`}>
      <header className={css.bar}>
        <button className={`ghost ${fieldsOpen ? css.on : ""}`} onClick={() => setFieldsOpen((v) => !v)} title="Show / hide fields (Ctrl+Shift+F)">
          ☰ Fields
        </button>
        <span className={css.title}>
          <span className={`mono ${css.key}`}>{title}</span>
          {!isCreate && form.summary && (
            <>
              <span className="muted">·</span>
              <span className={`muted ${css.ellipsis}`}>{form.summary}</span>
            </>
          )}
          {dirty && <span className={css.dot} title="Unsaved changes"></span>}
        </span>
        <span className={css.grow}></span>
        <button className="ghost" onClick={() => setFontSize((f) => Math.max(12, f - 1))} title="Smaller text">
          A−
        </button>
        <button className="ghost" onClick={() => setFontSize((f) => Math.min(28, f + 1))} title="Larger text">
          A+
        </button>
        <div className={css.modes} role="group" title="Description editor mode (Ctrl+P)">
          <button className={`ghost ${descMode === "rich" ? css.on : ""}`} onClick={() => descMode !== "rich" && toggleDescMode()} disabled={richBusy}>
            {richBusy && <span className="spin"></span>} Rich text
          </button>
          <button className={`ghost ${descMode === "markup" ? css.on : ""}`} onClick={() => descMode !== "markup" && toggleDescMode()} disabled={richBusy}>
            Markup
          </button>
        </div>
        <button className="ghost" onClick={() => void toggleOsFullscreen()} title="Toggle fullscreen (F11)">
          ⛶
        </button>
        <button className="ghost" onClick={cancel} disabled={saving}>
          Cancel
        </button>
        <button className="primary" onClick={() => void save()} disabled={saving || loading || (!isCreate && !dirty)} title="Save (Ctrl+S)">
          {saving && <span className="spin"></span>}
          {isCreate ? "Create" : "Save"}
        </button>
      </header>

      {confirmDiscard && (
        <div className={`${css.banner} ${css.warn}`}>
          Discard unsaved changes?
          <button onClick={() => app.closeEditor()}>Discard</button>
          <button className="ghost" onClick={() => setConfirmDiscard(false)}>
            Keep editing
          </button>
        </div>
      )}
      {saveError && <div className={`${css.banner} ${css.error}`}>{saveError}</div>}
      {lossy && descMode === "rich" && (
        <div className={`${css.banner} ${css.warn}`}>
          <span>
            This description uses markup the rich editor can't represent exactly (e.g. colors, panels, macros). Editing here will simplify it —
            switch to Markup to keep it verbatim.
          </span>
          <button className="ghost" onClick={toggleDescMode}>
            Edit markup
          </button>
          <button className="ghost" onClick={() => setLossy(false)}>
            Got it
          </button>
        </div>
      )}

      <div className={css.body}>
        {fieldsOpen && (
          <aside className={css.fields}>
            {loading ? (
              <div className="muted">
                <span className="spin"></span> Loading fields…
              </div>
            ) : loadError ? (
              <div className={css.errorText}>{loadError}</div>
            ) : (
              <>
                {isCreate && (
                  <>
                    <label>
                      <span>Project</span>
                      <select value={form.projectKey} onChange={(e) => onProjectChange(e.target.value)}>
                        {projects.map((p) => (
                          <option key={p.key} value={p.key}>
                            {p.key} · {p.name}
                          </option>
                        ))}
                      </select>
                    </label>
                    <label>
                      <span>Issue type</span>
                      <select value={form.issueTypeId} onChange={(e) => patch({ issueTypeId: e.target.value })} disabled={!issueTypes.length}>
                        {issueTypes.map((t) => (
                          <option key={t.id} value={t.id}>
                            {t.name}
                          </option>
                        ))}
                      </select>
                    </label>
                    {issueType?.subtask && (
                      <label>
                        <span>Parent issue</span>
                        <input value={form.parentKey} onChange={(e) => patch({ parentKey: e.target.value })} placeholder={`${form.projectKey}-123`} spellCheck={false} />
                      </label>
                    )}
                  </>
                )}

                {has("priority") && (
                  <label>
                    <span>Priority</span>
                    <select value={form.priorityId} onChange={(e) => patch({ priorityId: e.target.value })}>
                      {isCreate && <option value="">Default</option>}
                      {allowed("priority").map((p) => (
                        <option key={p.id} value={p.id}>
                          {p.name}
                        </option>
                      ))}
                    </select>
                  </label>
                )}

                {has("assignee") && (
                  <label className={css.assignee}>
                    <span>Assignee</span>
                    {!isCreate && original?.fields.assignee && !form.unassign && !form.assignee && (
                      <div className={`muted ${css.current}`}>Currently {original.fields.assignee.displayName}</div>
                    )}
                    <input
                      value={form.assignee}
                      onChange={(e) => onAssigneeInput(e.target.value)}
                      placeholder={form.unassign ? "Unassigned" : "username"}
                      spellCheck={false}
                      autoComplete="off"
                    />
                    {userHits.length > 0 && (
                      <div className={css.hits}>
                        {userHits.map((u) => (
                          <button
                            key={u.name}
                            className={`ghost ${css.hit}`}
                            onClick={() => {
                              patch({ assignee: u.name });
                              setUserHits([]);
                            }}
                          >
                            {u.displayName} <span className="muted">({u.name})</span>
                          </button>
                        ))}
                      </div>
                    )}
                    <div className={css.row}>
                      {me && (
                        <button className={`ghost ${css.small}`} onClick={() => patch({ assignee: me.name, unassign: false })}>
                          Me
                        </button>
                      )}
                      {!isCreate && (
                        <button className={`ghost ${css.small} ${form.unassign ? css.on : ""}`} onClick={() => patch({ unassign: !form.unassign, assignee: "" })}>
                          Unassign
                        </button>
                      )}
                    </div>
                  </label>
                )}

                {has("labels") && (
                  <label>
                    <span>Labels</span>
                    <input value={form.labels} onChange={(e) => patch({ labels: e.target.value })} placeholder="space separated" spellCheck={false} />
                  </label>
                )}

                {has("components") && allowed("components").length > 0 && (
                  <fieldset>
                    <legend>Components</legend>
                    {allowed("components").map((c) => (
                      <label key={c.id} className={css.check}>
                        <input type="checkbox" checked={form.componentIds.includes(c.id)} onChange={() => patch({ componentIds: toggleIn(form.componentIds, c.id) })} />
                        {c.name}
                      </label>
                    ))}
                  </fieldset>
                )}

                {has("fixVersions") && allowed("fixVersions").length > 0 && (
                  <fieldset>
                    <legend>Fix versions</legend>
                    {allowed("fixVersions").map((v) => (
                      <label key={v.id} className={css.check}>
                        <input type="checkbox" checked={form.fixVersionIds.includes(v.id)} onChange={() => patch({ fixVersionIds: toggleIn(form.fixVersionIds, v.id) })} />
                        {v.name}
                      </label>
                    ))}
                  </fieldset>
                )}

                {has("duedate") && (
                  <label>
                    <span>Due date</span>
                    <input type="date" value={form.duedate} onChange={(e) => patch({ duedate: e.target.value })} />
                  </label>
                )}

                {has("environment") && (
                  <label>
                    <span>Environment</span>
                    <textarea value={form.environment} onChange={(e) => patch({ environment: e.target.value })} rows={3} placeholder="Wiki markup"></textarea>
                  </label>
                )}
              </>
            )}
          </aside>
        )}

        <main className={css.zen}>
          {loading ? (
            <div className={`${css.center} muted`}>
              <span className="spin"></span>
            </div>
          ) : loadError && !isCreate ? (
            <div className={`${css.center} ${css.errorText}`}>{loadError}</div>
          ) : (
            <>
              <input
                ref={summaryInput}
                className={css.summary}
                value={form.summary}
                onChange={(e) => patch({ summary: e.target.value })}
                placeholder="Summary"
                style={{ fontSize: `${fontSize + 8}px` }}
                spellCheck
                autoFocus={isCreate}
              />
              {descMode === "rich" && richHtml !== null ? (
                <RichEditor
                  key={richKey}
                  contentKey={richKey}
                  html={richHtml}
                  fontSize={fontSize}
                  disabled={saving}
                  autoFocus={!isCreate}
                  onReady={onRichReady}
                  onChange={onRichChange}
                  onImageClick={openImage}
                />
              ) : (
                <textarea
                  ref={textarea}
                  className={css.markup}
                  value={form.description}
                  onChange={(e) => patch({ description: e.target.value })}
                  onKeyDown={insertTab}
                  style={{ fontSize: `${fontSize}px` }}
                  placeholder="Description in Jira wiki markup — h2. Heading, *bold*, _italic_, {code}…{code}, * bullets, [~user]"
                  spellCheck
                  disabled={saving}
                  autoFocus={!isCreate}
                ></textarea>
              )}
              <footer className={`${css.hint} muted`}>
                {descMode === "rich" ? "Rich text (saved as wiki markup)" : "Wiki markup"} · <kbd>Ctrl</kbd>+<kbd>S</kbd> save · <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd> fields ·{" "}
                <kbd>Ctrl</kbd>+<kbd>P</kbd> rich/markup · <kbd>Esc</kbd> cancel
                {descMode === "rich" && " · double-click an image to view it"}
              </footer>
            </>
          )}
        </main>
      </div>
    </div>
  );
}
