// src/App.tsx
import { lazy, Suspense, useEffect, useRef, useState } from "react";
import { getCurrentWindow } from "@tauri-apps/api/window";
import { app, useApp, useAppShallow } from "./lib/store";
import Connect from "./components/Connect";
import Sidebar from "./components/Sidebar";
import IssueList from "./components/IssueList";
import IssueView from "./components/IssueView";
import Lightbox from "./components/Lightbox";
import Toast from "./components/Toast";
import ShortcutsHelp from "./components/ShortcutsHelp";
import css from "./App.module.css";

// The editor pulls in TipTap/ProseMirror; keep it out of the startup bundle.
const IssueEditor = lazy(() => import("./components/IssueEditor"));

function isTyping(e: KeyboardEvent): boolean {
  const t = e.target as HTMLElement | null;
  if (!t) return false;
  const tag = t.tagName;
  return tag === "INPUT" || tag === "TEXTAREA" || tag === "SELECT" || t.isContentEditable;
}

async function toggleFullscreen() {
  const w = getCurrentWindow();
  await w.setFullscreen(!(await w.isFullscreen()));
}

export default function App() {
  const { screen, focus, sidebarOpen } = useAppShallow((s) => ({ screen: s.screen, focus: s.focus, sidebarOpen: s.sidebarOpen }));
  const editor = useApp((s) => s.editor);
  const [showHelp, setShowHelp] = useState(false);
  const searchBox = useRef<HTMLInputElement>(null);

  useEffect(() => {
    void app.init();
  }, []);

  useEffect(() => {
    function onKeydown(e: KeyboardEvent) {
      if (e.key === "F11") {
        e.preventDefault();
        void toggleFullscreen();
        return;
      }
      const s = app.state;
      if (s.screen !== "main" || s.editor || s.lightbox) return;
      if (e.key === "Escape") {
        if (showHelp) setShowHelp(false);
        else if (isTyping(e)) (e.target as HTMLElement).blur();
        else if (s.focus) app.setFocus(false);
        return;
      }
      if (isTyping(e) || e.ctrlKey || e.metaKey || e.altKey) return;
      switch (e.key) {
        case "j":
        case "ArrowDown":
          if (e.key === "ArrowDown" && s.focus) return;
          e.preventDefault();
          app.selectRelative(1);
          break;
        case "k":
        case "ArrowUp":
          if (e.key === "ArrowUp" && s.focus) return;
          e.preventDefault();
          app.selectRelative(-1);
          break;
        case "f":
          if (s.selectedKey) app.toggleFocus();
          break;
        case "/":
          e.preventDefault();
          app.setFocus(false);
          // The list mounts on the next frame when leaving focus mode.
          requestAnimationFrame(() => {
            searchBox.current?.focus();
            searchBox.current?.select();
          });
          break;
        case "r":
          void app.refreshList();
          void app.refreshIssue();
          break;
        case "b":
          app.toggleSidebar();
          break;
        case "c":
          if (s.issue) {
            e.preventDefault();
            window.dispatchEvent(new CustomEvent("jirafast:comment"));
          }
          break;
        case "u":
          app.back();
          break;
        case "e":
          if (s.selectedKey) {
            e.preventDefault();
            app.editIssue();
          }
          break;
        case "n":
          e.preventDefault();
          app.newIssue();
          break;
        case "?":
          setShowHelp((v) => !v);
          break;
      }
    }
    window.addEventListener("keydown", onKeydown);
    return () => window.removeEventListener("keydown", onKeydown);
  }, [showHelp]);

  return (
    <>
      {screen === "loading" ? (
        <div className={`${css.center} muted`}>Loading…</div>
      ) : screen === "connect" ? (
        <Connect />
      ) : (
        <>
          <div className={`${css.layout} ${focus ? css.focus : ""} ${!sidebarOpen ? css.noSidebar : ""}`}>
            {!focus && sidebarOpen && <Sidebar />}
            {!focus && <IssueList searchBox={searchBox} />}
            <IssueView />
          </div>
          {editor && (
            <Suspense fallback={<div className={`${css.overlay} muted`}>Loading editor…</div>}>
              <IssueEditor key={editor.kind === "edit" ? `edit:${editor.key}` : `create:${editor.projectKey ?? ""}`} mode={editor} />
            </Suspense>
          )}
          <Lightbox />
        </>
      )}

      <Toast />
      {showHelp && <ShortcutsHelp onClose={() => setShowHelp(false)} />}
    </>
  );
}

// src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { getCurrentWindow } from "@tauri-apps/api/window";
  import { app } from "./lib/store.svelte";
  import Connect from "./components/Connect.svelte";
  import Sidebar from "./components/Sidebar.svelte";
  import IssueList from "./components/IssueList.svelte";
  import IssueView from "./components/IssueView.svelte";
  import IssueEditor from "./components/IssueEditor.svelte";
  import Toast from "./components/Toast.svelte";
  import ShortcutsHelp from "./components/ShortcutsHelp.svelte";

  let showHelp = $state(false);
  let searchBox = $state<HTMLInputElement | null>(null);

  onMount(() => {
    void app.init();
  });

  function isTyping(e: KeyboardEvent): boolean {
    const t = e.target as HTMLElement | null;
    if (!t) return false;
    const tag = t.tagName;
    return tag === "INPUT" || tag === "TEXTAREA" || tag === "SELECT" || t.isContentEditable;
  }

  async function toggleFullscreen() {
    const w = getCurrentWindow();
    const fs = await w.isFullscreen();
    await w.setFullscreen(!fs);
  }

  function onKeydown(e: KeyboardEvent) {
    if (e.key === "F11") {
      e.preventDefault();
      void toggleFullscreen();
      return;
    }
    if (app.screen !== "main" || app.editor) return;
    if (e.key === "Escape") {
      if (showHelp) showHelp = false;
      else if (isTyping(e)) (e.target as HTMLElement).blur();
      else if (app.focus) app.focus = false;
      return;
    }
    if (isTyping(e) || e.ctrlKey || e.metaKey || e.altKey) return;
    switch (e.key) {
      case "j":
      case "ArrowDown":
        if (e.key === "ArrowDown" && app.focus) return;
        e.preventDefault();
        app.selectRelative(1);
        break;
      case "k":
      case "ArrowUp":
        if (e.key === "ArrowUp" && app.focus) return;
        e.preventDefault();
        app.selectRelative(-1);
        break;
      case "f":
        if (app.selectedKey) app.toggleFocus();
        break;
      case "/":
        e.preventDefault();
        app.focus = false;
        searchBox?.focus();
        searchBox?.select();
        break;
      case "r":
        void app.refreshList();
        void app.refreshIssue();
        break;
      case "b":
        app.sidebarOpen = !app.sidebarOpen;
        break;
      case "c":
        if (app.issue) {
          e.preventDefault();
          window.dispatchEvent(new CustomEvent("jirafast:comment"));
        }
        break;
      case "u":
        app.back();
        break;
      case "e":
        if (app.selectedKey) {
          e.preventDefault();
          app.editIssue();
        }
        break;
      case "n":
        e.preventDefault();
        app.newIssue();
        break;
      case "?":
        showHelp = !showHelp;
        break;
    }
  }
</script>

<svelte:window onkeydown={onKeydown} />

{#if app.screen === "loading"}
  <div class="center muted">Loading…</div>
{:else if app.screen === "connect"}
  <Connect />
{:else}
  <div class="layout" class:focus={app.focus} class:no-sidebar={!app.sidebarOpen}>
    {#if !app.focus && app.sidebarOpen}
      <Sidebar />
    {/if}
    {#if !app.focus}
      <IssueList bind:searchBox />
    {/if}
    <IssueView />
  </div>
  {#if app.editor}
    {#key app.editor}
      <IssueEditor mode={app.editor} />
    {/key}
  {/if}
{/if}

<Toast />
{#if showHelp}
  <ShortcutsHelp onclose={() => (showHelp = false)} />
{/if}

<style>
  .layout {
    display: grid;
    grid-template-columns: 220px minmax(320px, 420px) 1fr;
    height: 100vh;
    overflow: hidden;
  }
  .layout.no-sidebar {
    grid-template-columns: minmax(320px, 420px) 1fr;
  }
  .layout.focus {
    grid-template-columns: 1fr;
  }
  .center {
    display: grid;
    place-items: center;
    height: 100vh;
  }
</style>
